### ISSUE TITLE
Why does not support iOS 11?

### ISSUE THREAD

**Issue by yusuga** [MattLewin/NumericPicker#7]
NumericPicker supported iOS 10.3 in 1.0.1. The latest 1.1.0 supports only iOS 12, making it difficult to introduce to my project.

I would like to support iOS 11 if possible, but why is there a difficult reason?

**Comment by yusuga** [comment]
@MattLewin 

Thank you for your reply.
I'm sorry, my English isn't so good.

## About iOS version

I think it would be better to separately consider Swift version and iOS version.
Even though it [supports Swift 4.2](https://github.com/nvzqz/FileKit/blob/develop/.swift-version#L1) like [FileKit](https://github.com/nvzqz/FileKit), it is possible to [support older iOS](https://github.com/nvzqz/FileKit/blob/develop/FileKit.podspec#L8).

Even if the Deployment Target of NumeriPicker 1.1.0 is actually set to iOS 10.3, it can be compiled in Xcode 10's Swift 4.2 environment and it works normally.

| iOS 10.3.1 | iOS 11.4 | iOS 12 |
| --- | --- | --- |
| <img width="447" alt="2018-10-10 8 56 07" src="https://user-images.githubusercontent.com/724466/46706570-2ee58f80-cc70-11e8-9a30-8d8331ebb418.png"> | <img width="447" alt="2018-10-10 8 53 50" src="https://user-images.githubusercontent.com/724466/46706575-35740700-cc70-11e8-8361-ee88969eb75a.png"> | <img width="447" alt="2018-10-10 8 53 03" src="https://user-images.githubusercontent.com/724466/46706578-3a38bb00-cc70-11e8-8575-26b0146f6233.png"> |

## Problems

The case I am in trouble is that in iOS 11 and Swift 4.2 environment, I can not use NumericPicker 1.1.0. In that case, I use NumericPicker 1.0.1 (using Swift 4.0), but this may cause problems in the future. When the Swift 4.0 compiler is removed from Xcode, I need to raise the iOS version supported by that project to 12

## Suggest a solution

Because NumeriPicker 1.1.0 works properly on iOS 10.3, I suggest to [return to 10.3](https://github.com/MattLewin/NumericPicker/blob/master/NumericPicker.podspec#L28)

---

In English this explanation was difficult, but I pray for being transmitted.

**Comment by MattLewin** [comment]
@yusuga, don't underestimate yourself -- your explanation was great.

I appreciate your input. I will likely just follow your advice and release a 1.1.1 version that returns support for iOS 10.3+, Swift 4.2 and Xcode 10, while leaving 1.0.1 to support iOS 10.3+, Swift 4.0 and Xcode 9.3.

I have a few other things going on, so it may take me a few days to get to it. Until I am able to do this, are you able to use the 1.0.1 version with your app? If not, *please* let me know, and I can see if I can find the cycles to get this done more quickly.

Alternatively, if you want to make the changes yourself and submit a PR, I would welcome it. (_hint hint_)

**Comment by MattLewin** [comment]
@yusuga, I lied. I will probably release 1.1.1 with the above changes tomorrow (U.S. East Coast time). It's obviously easy to switch the supported iOS version to 10.3. I just want to run through all my testing. Thanks for your patience.

**Comment by yusuga** [comment]
@MattLewin Thank you for your quick response. 
I'm not in a hurry, so I'm look forward to 1.1.1 😄

**Comment by yusuga** [comment]
Oh, 1.1.1 was already released. Thanks!
